"""Validation on the independent generator: the engine, three naive baselines, a family
ablation, the +/-20% threshold sweep and Wilson intervals, over many seeds.

`satsa validate-independent` runs this. Each seed is generated by
`satsa.synth.independent.IndependentScenarioGenerator`, ingested and assessed in its own
temporary store, so nothing touches `data/`. Every figure in the report is computed here from
those runs.
"""

from __future__ import annotations

import json
import platform
import tempfile
import time
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from satsa.ingest.pipeline import IngestionPipeline
from satsa.scoring.runner import AssessmentRunner
from satsa.store.duckdb import DuckDBStore
from satsa.store.sqlite import SQLiteStore
from satsa.synth.independent import GENERATOR_VERSION, IndependentScenarioGenerator
from satsa.validate.baselines import BASELINES, run_baselines
from satsa.validate.harness import ValidationHarness, wilson_interval

FAMILIES = {"EG": "Execution gaps (EG01-EG12)", "NS": "Negative space (NS01-NS08)"}


def _precision_at_k(ranked: list[tuple[str, float]], positives: set[str]) -> tuple[float, int]:
    """Expected number of positives in the top k (k = number of positives), averaging over
    the order of tied scores at the cut-off. Returns (expected hits, k)."""
    k = len(positives)
    if k == 0:
        return 0.0, 0
    ordered = sorted(ranked, key=lambda x: -x[1])
    hits, taken, i = 0.0, 0, 0
    while i < len(ordered) and taken < k:
        tie = [e for e, s in ordered if s == ordered[i][1]]
        slots = min(k - taken, len(tie))
        pos_in_tie = sum(1 for e in tie if e in positives)
        hits += slots * pos_in_tie / len(tie)
        taken += slots
        i += len(tie)
    return hits, k


def _score_pairs(found: set[tuple[str, str]], gt: dict[str, Any]) -> dict[str, Any]:
    defects = {(d["entity_id"], d["rule_id"]) for d in gt["defects"]}
    decoys = {(d["entity_id"], d["rule_id"]) for d in gt["decoys"]}
    clean = set(gt["clean_entities"])
    per_rule: dict[str, dict[str, int]] = defaultdict(lambda: {"tp": 0, "fn": 0, "fp": 0, "decoys": 0, "decoys_flagged": 0})
    for pair in defects:
        per_rule[pair[1]]["tp" if pair in found else "fn"] += 1
    for pair in found - defects:
        per_rule[pair[1]]["fp"] += 1
    for pair in decoys:
        per_rule[pair[1]]["decoys"] += 1
        per_rule[pair[1]]["decoys_flagged"] += pair in found
    fp = found - defects
    return {
        "tp": len(found & defects), "fn": len(defects - found), "fp": len(fp),
        "fp_on_decoys": len(fp & decoys), "fp_on_clean": sum(1 for e, _ in fp if e in clean),
        "decoys": len(decoys), "decoys_flagged": len(found & decoys),
        "clean_entities": len(clean), "clean_flagged": len({e for e, _ in found if e in clean}),
        "missed": sorted(f"{e}:{r}" for e, r in defects - found),
        "false_positives": sorted(f"{e}:{r}" for e, r in fp),
        "per_rule": {r: dict(v) for r, v in sorted(per_rule.items())},
    }


def run_seed(seed: int, rules_config: str = "config/rules.yaml", sweep: bool = True) -> dict[str, Any]:
    """Generate, ingest and assess one independent scenario; score the engine and baselines."""
    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="satsa-ind-") as tmp:
        tmp_path = Path(tmp)
        csv_dir, gt_path = IndependentScenarioGenerator(seed).save(tmp_path / "gen")
        gt = json.loads(gt_path.read_text(encoding="utf-8"))
        duck = DuckDBStore(tmp_path / "store")
        sql = SQLiteStore(tmp_path / "store" / "independent.db")
        try:
            IngestionPipeline(duck, sql).ingest_directory(csv_dir)
            runner = AssessmentRunner(duck, sql, rules_config_path=rules_config)
            res = runner.run_assessment(period="INDEPENDENT", actor="cli:validate-independent")
            run_id = res["run_id"]
            rows = sql.conn.execute("SELECT entity_id, rule_id FROM findings WHERE run_id = ?", (run_id,)).fetchall()
            found = {(r["entity_id"], r["rule_id"]) for r in rows}
            engine = _score_pairs(found, gt)

            defect_entities = {d["entity_id"] for d in gt["defects"]}
            scores = [(e, float(v["risk_index"])) for e, v in res["entity_scores"].items()]
            hits, k = _precision_at_k(scores, defect_entities)
            engine["ranking"] = {"hits": hits, "k": k}

            # Design margin: recall for share-based defects by how far over the threshold they were built.
            margins = []
            for d in gt["defects"]:
                f = (d.get("measured") or {}).get("design_factor")
                if f is not None:
                    margins.append({"rule_id": d["rule_id"], "factor": f, "detected": (d["entity_id"], d["rule_id"]) in found})
            engine["margins"] = margins

            # Systemic: expected groups detected, decoy pairs flagged.
            systemic = sql.get_systemic_findings(run_id)
            got = [(s["rule_id"], s.get("shared_value"), set(s.get("entity_ids") or [])) for s in systemic]
            exp = gt["systemic_expected"]
            sys_tp = sum(1 for x in exp if any(r == x["rule_id"] and set(x["entities"]) <= ents for r, _v, ents in got))
            sys_fp = sum(1 for r, v, ents in got if not any(r == x["rule_id"] and set(x["entities"]) <= ents for x in exp))
            engine["systemic"] = {"expected": len(exp), "detected": sys_tp, "other_systemic_findings": sys_fp,
                                  "decoy_pairs_flagged": sum(1 for x in gt["systemic_decoys"]
                                                             if any(r == x["rule_id"] and set(x["entities"]) <= ents for r, _v, ents in got))}

            # Baselines on the same store.
            base_flags = run_baselines(duck)
            baselines = {}
            for name, meta in BASELINES.items():
                rule = meta["maps_to"]
                pairs = {(e, rule) for e in base_flags[name]}
                truth = {(d["entity_id"], d["rule_id"]) for d in gt["defects"] if d["rule_id"] == rule}
                decoys = {(d["entity_id"], d["rule_id"]) for d in gt["decoys"] if d["rule_id"] == rule}
                engine_pairs = {p for p in found if p[1] == rule}
                baselines[name] = {
                    "maps_to": rule,
                    "baseline": {"tp": len(pairs & truth), "fp": len(pairs - truth), "fn": len(truth - pairs),
                                 "decoys_flagged": len(pairs & decoys), "flagged": len(pairs)},
                    "engine": {"tp": len(engine_pairs & truth), "fp": len(engine_pairs - truth), "fn": len(truth - engine_pairs),
                               "decoys_flagged": len(engine_pairs & decoys), "flagged": len(engine_pairs)},
                }
            flag_count = {e: 0.0 for e in res["entity_scores"]}
            for flagged in base_flags.values():
                for e in flagged:
                    flag_count[e] = flag_count.get(e, 0.0) + 1
            b_hits, b_k = _precision_at_k(list(flag_count.items()), defect_entities)
            baselines["_ranking"] = {"hits": b_hits, "k": b_k}

            # Ablation: the same store, scored without one rule family (dry run, nothing persisted).
            ablation = {}
            for fam in FAMILIES:
                abl = AssessmentRunner(duck, sql, rules_config_path=rules_config)
                abl.registry.rules = {rid: r for rid, r in abl.registry.rules.items() if not rid.startswith(fam)}
                dry = abl.run_assessment(period="ABLATION", dry_run=True, refresh_tables=False)
                abl_found = {(f["entity_id"], f["rule_id"]) for f in dry["findings"]}
                scored = _score_pairs(abl_found, gt)
                a_hits, a_k = _precision_at_k([(e, float(v["risk_index"])) for e, v in dry["entity_scores"].items()],
                                              defect_entities)
                scored["ranking"] = {"hits": a_hits, "k": a_k}
                scored["systemic_findings"] = dry.get("systemic_findings_count", 0)
                ablation[fam] = scored

            sens = None
            if sweep:
                harness = ValidationHarness(duck, sql, gt_path)
                raw = harness.evaluate_threshold_sensitivity(rules_config)
                sens = [{"rule_id": r["rule_id"], "param": r["param"], "change": r["change"], "changed": r["changed"],
                         "new_fn": sorted(set(r["outcome"]["fn"]) - set(r["baseline_outcome"]["fn"])),
                         "new_fp": sorted(set(r["outcome"]["fp"]) - set(r["baseline_outcome"]["fp"]))}
                        for r in raw["rows"]]
        finally:
            duck.close()
            sql.close()
    return {
        "seed": seed, "seconds": round(time.perf_counter() - started, 1),
        "defects": len(gt["defects"]), "decoys": len(gt["decoys"]),
        "relabelled": gt["relabelled"], "incidental": [f"{d['entity_id']}:{d['rule_id']}" for d in gt["defects"]
                                                        if d["defect_type"] in ("incidental", "decoy_met_criterion")],
        "engine": engine, "baselines": baselines, "ablation": ablation, "sensitivity": sens,
    }


# ------------------------------------------------------------------ aggregation and report


def _ci(num: float, den: float) -> str:
    """Percentage, counts and 95% Wilson interval. A fractional numerator (ranking hits averaged
    over tied scores) is rounded to the nearest whole count for the interval only."""
    if not den:
        return "n/a"
    iv = wilson_interval(round(num), int(den))
    pct = 100.0 * num / den
    shown = f"{num:g}" if float(num).is_integer() else f"{num:.1f}"
    return f"{pct:.1f}% ({shown}/{den:g}; 95% CI {iv[0] * 100:.1f}-{iv[1] * 100:.1f}%)" if iv else f"{pct:.1f}%"


def aggregate(results: list[dict[str, Any]]) -> dict[str, Any]:
    tot: dict[str, float] = defaultdict(float)
    per_rule: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for r in results:
        e = r["engine"]
        for key in ("tp", "fn", "fp", "fp_on_decoys", "fp_on_clean", "decoys", "decoys_flagged", "clean_entities", "clean_flagged"):
            tot[key] += e[key]
        tot["rank_hits"] += e["ranking"]["hits"]
        tot["rank_k"] += e["ranking"]["k"]
        for rule, c in e["per_rule"].items():
            for key, v in c.items():
                per_rule[rule][key] += v
    base: dict[str, dict[str, dict[str, int]]] = {}
    for name in BASELINES:
        base[name] = {"baseline": defaultdict(int), "engine": defaultdict(int)}
        for r in results:
            for side in ("baseline", "engine"):
                for key, v in r["baselines"][name][side].items():
                    base[name][side][key] += v
    base_rank = (sum(r["baselines"]["_ranking"]["hits"] for r in results), sum(r["baselines"]["_ranking"]["k"] for r in results))
    abl: dict[str, dict[str, float]] = {}
    for fam in FAMILIES:
        a: dict[str, float] = defaultdict(float)
        for r in results:
            x = r["ablation"][fam]
            for key in ("tp", "fn", "fp", "fp_on_decoys", "fp_on_clean", "clean_flagged"):
                a[key] += x[key]
            a["rank_hits"] += x["ranking"]["hits"]
            a["rank_k"] += x["ranking"]["k"]
            a["systemic_findings"] += x["systemic_findings"]
        abl[fam] = dict(a)
    systemic: dict[str, int] = defaultdict(int)
    for r in results:
        for name, v in r["engine"]["systemic"].items():
            systemic[name] += v
    margins: dict[str, list[int]] = {"1.08-1.30": [0, 0], "1.30-1.60": [0, 0], "1.60-1.90": [0, 0]}
    for r in results:
        for m in r["engine"]["margins"]:
            b = "1.08-1.30" if m["factor"] < 1.30 else "1.30-1.60" if m["factor"] < 1.60 else "1.60-1.90"
            margins[b][0] += m["detected"]
            margins[b][1] += 1
    sweep: dict[tuple[str, str, str], dict[str, Any]] = {}
    for r in results:
        for row in r["sensitivity"] or []:
            cell = (row["rule_id"], row["param"], row["change"])
            s = sweep.setdefault(cell, {"runs_changed": 0, "new_fn": 0, "new_fp": 0, "runs": 0})
            s["runs"] += 1
            s["runs_changed"] += row["changed"]
            s["new_fn"] += len(row["new_fn"])
            s["new_fp"] += len(row["new_fp"])
    relabelled: dict[str, int] = defaultdict(int)
    for r in results:
        for x in r["relabelled"]:
            relabelled[f"{x['rule_id']}: {x['built_as']} -> {x['labelled']}"] += 1
    return {"totals": dict(tot), "per_rule": {k: dict(v) for k, v in sorted(per_rule.items())},
            "baselines": {k: {s: dict(v) for s, v in d.items()} for k, d in base.items()}, "baseline_ranking": base_rank,
            "ablation": abl, "systemic": dict(systemic), "margins": margins, "sweep": sweep,
            "relabelled": dict(sorted(relabelled.items()))}


def render_markdown(results: list[dict[str, Any]], agg: dict[str, Any], command: str) -> str:
    t = agg["totals"]
    seeds = [r["seed"] for r in results]
    lines = [
        "# SAT-SA Validation on an Independent Generator",
        "",
        "> **Supervisory Notice:** *Indicators requiring supervisory review; not a compliance determination.*",
        "",
        "> **Synthetic data only; a real-data pilot is still pending.** This is a second synthetic",
        "> generator, written separately from the first; it is not real SOC data.",
        "",
        f"Generated {datetime.now(UTC).strftime('%Y-%m-%d')} by:",
        "",
        "```",
        command,
        "```",
        "",
        (f"Generator `{GENERATOR_VERSION}` (`src/satsa/synth/independent.py`), {len(results)} seeds "
         f"({min(seeds)}-{max(seeds)}), 15 entities per seed. Python {platform.python_version()}. "
         "Every number below is computed by that command from those runs."),
        "",
        "## 1. How the data was built",
        "",
        "The generator was written from the rule descriptions in README.md and",
        "docs/analytics_methodology.md Section 3 and the thresholds stated there; it imports nothing",
        "from the original generator or the rules. Per seed: 15 entities `ORG-A`..`ORG-O` (every",
        "sector at every size band), April-September 2026, 350-3,500 alerts each (lognormal), 4-22",
        "analysts each, every rule's defect placed on a random entity and built 1.08-1.9x over its",
        "documented threshold, a **decoy** for most rules built just under it on another entity, a",
        "three-entity systemic group and a two-entity systemic decoy. EG11 has two documented forms",
        "and is built in either, chosen per seed: no true positives at all, or a skewed",
        "false-positive rate with a few true positives (1-2.5% of alerts), which only the robust-z",
        "branch can catch. For NS03, EG11 and EG05 the generator then computes each rule's",
        "documented criterion on the data it built and labels the ground truth by it (Section 6).",
        "",
        "## 2. Engine results (all seeds pooled, 95% Wilson intervals)",
        "",
        "| Measure | Result |",
        "|---|---|",
        f"| Recall (defects detected) | {_ci(t['tp'], t['tp'] + t['fn'])} |",
        f"| Precision (findings that are a defect) | {_ci(t['tp'], t['tp'] + t['fp'])} |",
        f"| Decoys flagged (built just under a threshold) | {_ci(t['decoys_flagged'], t['decoys'])} |",
        f"| False positives not on a decoy | {t['fp'] - t['fp_on_decoys']:g} |",
        f"| Clean entities flagged by any rule | {_ci(t['clean_flagged'], t['clean_entities'])} |",
        f"| Entity ranking precision@k (k = defect entities) | {_ci(t['rank_hits'], t['rank_k'])} |",
        "",
        "### Per rule",
        "",
        "| Rule | Detected | Recall (95% CI) | False positives | Precision (95% CI) | Decoys flagged |",
        "|---|---:|---|---:|---|---|",
    ]
    for rule, c in agg["per_rule"].items():
        n = c.get("tp", 0) + c.get("fn", 0)
        lines.append(f"| {rule} | {c.get('tp', 0)}/{n} | {_ci(c.get('tp', 0), n)} | {c.get('fp', 0)} | "
                     f"{_ci(c.get('tp', 0), c.get('tp', 0) + c.get('fp', 0))} | {c.get('decoys_flagged', 0)}/{c.get('decoys', 0)} |")
    lines += ["", "### Recall by how far over the threshold a defect was built (EG01, EG02, EG04, NS05)", "",
              "| Built at (x threshold) | Detected |", "|---|---|"]
    for band, (hit, n) in agg["margins"].items():
        lines.append(f"| {band} | {_ci(hit, n)} |")
    s = agg["systemic"]
    lines += ["", "### Systemic (cross-entity) detector", "",
              (f"Expected groups detected: {s.get('detected', 0)} of {s.get('expected', 0)}. Systemic decoy pairs "
               f"(2 entities, below the 3-entity minimum) flagged: {s.get('decoy_pairs_flagged', 0)} of {len(results)}. "
               f"Other systemic findings: {s.get('other_systemic_findings', 0)}."), ""]

    lines += ["## 3. Naive baselines on the same data", "",
              "Each baseline is one fixed threshold on one metric (`src/satsa/validate/baselines.py`), scored",
              "against the ground truth of the engine rule that tests the same idea.", "",
              "| Baseline | Compared with | Baseline recall | Baseline precision | Baseline decoys flagged | Engine recall | Engine precision | Engine decoys flagged |",
              "|---|---|---|---|---|---|---|---|"]
    verdicts = []
    for name, meta in BASELINES.items():
        b = agg["baselines"][name]["baseline"]
        e = agg["baselines"][name]["engine"]
        lines.append(f"| `{name}` ({meta['description']}) | {meta['maps_to']} | {_ci(b['tp'], b['tp'] + b['fn'])} | "
                     f"{_ci(b['tp'], b['tp'] + b['fp'])} | {b['decoys_flagged']} | {_ci(e['tp'], e['tp'] + e['fn'])} | "
                     f"{_ci(e['tp'], e['tp'] + e['fp'])} | {e['decoys_flagged']} |")
        b_rec = b["tp"] / max(b["tp"] + b["fn"], 1)
        e_rec = e["tp"] / max(e["tp"] + e["fn"], 1)
        b_pre = b["tp"] / max(b["tp"] + b["fp"], 1)
        e_pre = e["tp"] / max(e["tp"] + e["fp"], 1)
        rec = "ties" if abs(b_rec - e_rec) < 1e-9 else ("wins" if b_rec > e_rec else "loses")
        pre = "ties" if abs(b_pre - e_pre) < 1e-9 else ("wins" if b_pre > e_pre else "loses")
        verdicts.append(f"- `{name}` vs {meta['maps_to']}: the baseline **{rec}** on recall and **{pre}** on precision.")
    bh, bk = agg["baseline_ranking"]
    lines += ["", *verdicts, "",
              (f"Entity ranking by number of baseline flags (ties averaged): precision@k {_ci(bh, bk)}; "
               f"engine: {_ci(t['rank_hits'], t['rank_k'])}."), ""]

    lines += ["## 4. Ablation: one rule family removed", "",
              "The same stores, scored again without one family (dry run). Defects of the removed family",
              "count as missed. Removing the systemic detector changes no per-entity finding; its own",
              "result is in Section 2.", "",
              "| Configuration | Recall | Precision | False positives | Clean entities flagged | Ranking precision@k |",
              "|---|---|---|---:|---|---|",
              (f"| All 20 rules | {_ci(t['tp'], t['tp'] + t['fn'])} | {_ci(t['tp'], t['tp'] + t['fp'])} | {t['fp']:g} | "
               f"{t['clean_flagged']:g}/{t['clean_entities']:g} | {_ci(t['rank_hits'], t['rank_k'])} |")]
    for fam, label in FAMILIES.items():
        a = agg["ablation"][fam]
        lines.append(f"| Without {label} | {_ci(a['tp'], a['tp'] + a['fn'])} | {_ci(a['tp'], a['tp'] + a['fp'])} | "
                     f"{a['fp']:g} | {a['clean_flagged']:g}/{t['clean_entities']:g} | {_ci(a['rank_hits'], a['rank_k'])} |")

    lines += ["", "## 5. Threshold sweep (+/-20%, one threshold at a time)", "",
              "For each tunable threshold, in how many seeds a 20% move changed which entities the rule flags,",
              "and how many defects it lost and false alarms (decoys included) it added in total.", "",
              "| Rule | Threshold | Move | Seeds changed | Defects lost | False alarms added |", "|---|---|---|---:|---:|---:|"]
    for (rule, param, change), s2 in sorted(agg["sweep"].items()):
        if s2["runs_changed"]:
            lines.append(f"| {rule} | `{param}` | {change} | {s2['runs_changed']} of {s2['runs']} | {s2['new_fn']} | {s2['new_fp']} |")
    lines += ["", "Moves not listed changed nothing in any seed.", ""]

    lines += ["## 6. Ground truth relabelled by the documented criterion", "",
              "| Rule: built as -> labelled | Times |", "|---|---:|"]
    for key, n in agg["relabelled"].items():
        lines.append(f"| {key} | {n} |")
    if not agg["relabelled"]:
        lines.append("| none | 0 |")
    lines += ["", "A *baseline -> defect* row means an entity that nobody built a defect into meets the",
              "documented criterion by chance. These count as defects in Section 2: the rule is right to",
              "flag them under its own specification, which says something about the specification",
              "(`docs/threshold_rationale.md`).", "",
              "## 7. Per seed", "", "| Seed | Defects | Decoys | Detected | False positives | Missed | Seconds |",
              "|---:|---:|---:|---:|---:|---|---:|"]
    for r in results:
        e = r["engine"]
        lines.append(f"| {r['seed']} | {r['defects']} | {r['decoys']} | {e['tp']} | {e['fp']} | {', '.join(e['missed']) or '-'} | {r['seconds']} |")
    lines += ["", "False positives per seed: " + "; ".join(
        f"{r['seed']}: {', '.join(r['engine']['false_positives']) or '-'}" for r in results), ""]
    lines += WHAT_THIS_PROVES
    return "\n".join(lines) + "\n"


WHAT_THIS_PROVES = [
    "## 8. What this does and does not prove",
    "",
    "**It does show:**",
    "",
    "- Whether the rules, as implemented, flag the conditions their documentation describes when the",
    "  data comes from a generator written from that documentation rather than from the rule code:",
    "  different entity names, volumes, mixes, timing and defect sizes, chosen per seed.",
    "- How the rules behave just under their thresholds (decoys), not only well over them.",
    "- Whether the 20-rule engine does better than one-line rules on the same data, and what each rule",
    "  family contributes (Sections 3 and 4).",
    "- Where documentation and code disagree: a rule whose recall or precision falls short here either",
    "  has a defect or a specification that does not say what the code does.",
    "",
    "**It does not show:**",
    "",
    "- **Accuracy on real SOC data.** Both generators are synthetic. Real submissions have missing",
    "  fields, tool-specific workflows and defects nobody wrote down.",
    "- **Independence of mind.** The generator was written by the same AI-assisted team that wrote the",
    "  rules, in a session that had read the rule code. It is independent of the original generator's",
    "  code, not of knowledge of the thresholds. Where the documentation was silent about a column",
    "  (for example which closure column holds the comment length), the canonical schema was used.",
    "- **That the thresholds are right.** Decoys sit just under the documented thresholds; whether those",
    "  thresholds separate good and poor SOC practice is a question for real data",
    "  (`docs/threshold_rationale.md`).",
    "- **The base rate of defects.** Every seed carries at least one defect for every rule, far more",
    "  than a real portfolio would; precision on real data would differ.",
    "- **Recall for defect types outside the rule catalogue.** The generator builds only what the",
    "  documentation describes.",
    "",
]
